Kyle Timmermans - Dr. Li - Homework #1 - 2/28/21


In [5]:
import numpy as np    # Need to import numpy

Question 1: Create a one-dimensional array, A1, with 20 random integers between -10 and 10

In [72]:
A1 = np.random.randint(-10, high=10, size=20)   # (Lowest, highest, num of elements)
print(A1)   # Print result

[ 0  7  8  6  2 -3 -7 -1  8 -2 -9  3 -2 -8 -3 -3  3 -7 -2 -4]


Question 1-1: Increase all of them by 2

In [73]:
A1 = A1 + 2   # A1 + 2 adds two to each element
print(A1)   # Print result

[ 2  9 10  8  4 -1 -5  1 10  0 -7  5  0 -6 -1 -1  5 -5  0 -2]


Question 1-2: Show the last 5 elements

In [74]:
print(A1[-5:])    # Slice with -5 being the last 5 elements (-5 from end, to end)

[-1  5 -5  0 -2]


Question 2: Create a 5 by 4 dimensional array, A2, with 20 random integers less than 10

In [75]:
A2 = (np.random.randint(10, size=20)).reshape(5,4)    # Reshape used to change dimensions of 2D array
print(A2)   # Print results

[[9 4 8 1]
 [8 1 7 2]
 [3 5 3 3]
 [4 4 2 5]
 [3 1 6 7]]


Question 2-1: Show only the 1st, 3rd columns.

*Not sure if that means 1 THROUGH 3 or 1 AND 3, did both just in case*

In [76]:
print(A2[:, 0:3])   # 1st column THROUGH 3rd column

[[9 4 8]
 [8 1 7]
 [3 5 3]
 [4 4 2]
 [3 1 6]]


In [77]:
print(A2[:, [0,2]])   # 1st column AND 3rd column

[[9 8]
 [8 7]
 [3 3]
 [4 2]
 [3 6]]


Question 2-2: Get the last two columns of the first two rows.

In [78]:
print(A2[:2, 2:4])   # Need top-right 4

[[8 1]
 [7 2]]


Question 2-3: Check whether the first element of A1 is in A2.

In [90]:
firstIndexOfA1 = A1[0]   # Without using if statement
A2ToBoolean = np.array(A2)
print("Does A2 contain the first index of A1? Yes, looking at the table below, A1[0] shows up twice in A2")
print(str(A2ToBoolean == firstIndexOfA1))  # Get boolean values and check if A1[0] is contained in A2


Does A2 contain the first index of A1? Yes, looking at the table below, A1[0] shows up twice in A2
[[False False False False]
 [False False False  True]
 [False False False False]
 [False False  True False]
 [False False False False]]


Question 2-4: Reshape the first array you created to the same shape as this one, compare the two arrays element-wise maximum. 

In [92]:
A1 = A1.reshape(5,4)    # Reshape A1 to same as A2
print(np.maximum(A1,A2))    # element-wise comparison using np.maximum()

[[ 9  9 10  8]
 [ 8  1  7  2]
 [10  5  3  5]
 [ 4  4  2  5]
 [ 5  1  6  7]]


Question 2-5: If the element in A1's first column is positive, show elements in A2 as the same row as that element.

In [99]:
FirstColumnOfA1 = np.where(A1[:,0] >= 0)   # Find all values greater than or equal to 0 (not-negative) in A1's first column
A1ToA2 = A2[FirstColumnOfA1, 0]   # Get corresponding A2 element (matching A1 position to A2 position)
print("A1 Array:")
print(A1)
print("A2 Array:")
print(A2)
print("Final output: ")   # Print all of A2 column 1 because there are no negatives in A1 column 1
print(np.squeeze(A1ToA2))  # Show only the A2 values


A1 Array:
[[ 2  9 10  8]
 [ 4 -1 -5  1]
 [10  0 -7  5]
 [ 0 -6 -1 -1]
 [ 5 -5  0 -2]]
A2 Array:
[[9 4 8 1]
 [8 1 7 2]
 [3 5 3 3]
 [4 4 2 5]
 [3 1 6 7]]
Final output: 
[9 8 3 4 3]
